services:
  postgres:
    image: postgres:14.17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    env_file:
      - .env
    ports:
      - "4455:4455"
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm start"

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - postgres
      - backend
    command: sh -c "npx prisma generate && npx prisma studio --port 5555 --browser none"

volumes:
  postgres-data:
